### PR TITLE
Add .intersection(r)

### PR DESCRIPTION
**Pull request by lovasoa**
Add Rectangle.prototype.intersection(Rectangle) that computes the
intersection of two rectangles.

The method returns null if the two rectangles don't intersect. Maybe it should return a new Rectangle(0,0,0,0) in this case to make chaining methods easier.

### CODE REVIEW

**Comment by rahatarmanahmed** [comment]
Whoa. I totally forgot I made this module. Thanks for the PR, I'll check it out later today when I'm free but it looks good.

Out of curiosity, what are you using this module for?

**Comment by lovasoa** [comment]
I want to implement a genetic rectangle packing in javascript and see how well it performs.

**Comment by rahatarmanahmed** [comment]
Thanks for your conribution!

**Comment by lovasoa** [comment]
Thanks for the software!
Here is my [genetic rectangle packer](http://lovasoa.github.io/genetic-rectangle-packer/).
Unfortunately, I ended up not using this lib :(

**Comment by rahatarmanahmed** [comment]
Very cool, and thats okay. I never used it either, lol.

**Pull request merged**
